[package]
name = "vax"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
edition = "2018"

[dependencies]
maplit = "1.0.1"
vax-derive = { path = "vax-codegen" }

[workspace]
members = [
    "vax-codegen"
]
