[package]
name = "wonderbox"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
edition = "2018"

[dependencies]
wonderbox-codegen = { path = "wonderbox-codegen" }

[workspace]
members = [
    "wonderbox-codegen"
]
