[package]
name = "wonderbox-codegen"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.12"

[dependencies.syn]
version = "0.15.33"
features = ["full", "extra-traits"]
